"""Read-only lifecycle artifact generation from canonical project state."""
from __future__ import annotations

from datetime import datetime, timezone
import json
from typing import Any, Mapping

from flow_of_work_mcp.core.domain import (
    ArtifactDraft,
    ArtifactGeneration,
    ArtifactKind,
    ArtifactMapping,
)
from flow_of_work_mcp.core.domain.identifiers import required_text
from flow_of_work_mcp.core.ports import (
    ArtifactRepository,
    GoalGraphRepository,
    LedgerVersionReader,
    LifecycleControlRepository,
    RequirementLedger,
)
from flow_of_work_mcp.core.standards import StandardProfileRegistry


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")


class ArtifactGenerationService:
    """Materialize profile-defined views without turning documents into authority."""

    def __init__(
        self,
        *,
        profiles: StandardProfileRegistry,
        requirements: RequirementLedger,
        goals: GoalGraphRepository,
        control: LifecycleControlRepository,
        ledger_versions: LedgerVersionReader,
        artifacts: ArtifactRepository,
    ) -> None:
        self._profiles = profiles
        self._requirements = requirements
        self._goals = goals
        self._control = control
        self._ledger_versions = ledger_versions
        self._artifacts = artifacts

    def generate(
        self,
        project_id: str,
        *,
        profile_id: str,
        actor: str,
        request_id: str = "",
    ) -> ArtifactGeneration:
        profile = self._profiles.get(profile_id)
        requirements = self._requirements.traceability_matrix(project_id)
        graph = self._goals.goal_graph(project_id)
        milestones = self._control.milestones(project_id)
        phase_audits = self._control.all_phase_audits(project_id)
        source_ledger_version = self._ledger_versions.ledger_version(project_id)
        generated_at = _utc_now()
        context = {
            "project_id": project_id,
            "profile_id": profile.profile_id,
            "profile_version": profile.version,
            "source_ledger_version": source_ledger_version,
            "generated_at": generated_at,
            "requirements": requirements,
            "graph": graph,
            "milestones": milestones,
            "phase_audits": phase_audits,
        }
        artifacts = tuple(
            self._render(ArtifactKind(kind), context)
            for kind in profile.generated_artifacts
        )
        generation = ArtifactGeneration(
            project_id=project_id,
            profile_id=profile.profile_id,
            profile_version=profile.version,
            source_ledger_version=source_ledger_version,
            generated_at=generated_at,
            artifacts=artifacts,
        )
        return self._artifacts.record_artifact_generation(
            generation,
            actor=required_text(actor, "actor"),
            request_id=str(request_id or ""),
        )

    def _render(self, kind: ArtifactKind, context: Mapping[str, Any]) -> ArtifactDraft:
        renderers = {
            ArtifactKind.SRS: self._render_srs,
            ArtifactKind.REQUIREMENTS_CATALOGUE: self._render_requirements_catalogue,
            ArtifactKind.USE_CASE_SPECIFICATION: self._render_use_cases,
            ArtifactKind.SEQUENCE_SPECIFICATION: self._render_sequences,
            ArtifactKind.TRACEABILITY_MATRIX: self._render_traceability,
            ArtifactKind.MILESTONE_AUDIT: self._render_milestones,
            ArtifactKind.PHASE_AUDIT: self._render_phase_audits,
        }
        try:
            return renderers[kind](context)
        except KeyError as exc:
            raise ValueError(f"unsupported generated artifact kind: {kind}") from exc

    @staticmethod
    def _header(title: str, context: Mapping[str, Any]) -> list[str]:
        return [
            "<!-- Generated by Flower MCP. Do not edit as authority. -->",
            f"# {title}",
            "",
            f"- Project: `{context['project_id']}`",
            f"- Standard profile: `{context['profile_id']}@{context['profile_version']}`",
            f"- Baseline revision: `ledger-{context['source_ledger_version']}`",
            f"- Source ledger version: `{context['source_ledger_version']}`",
            f"- Generated at: `{context['generated_at']}`",
            "- Authority: canonical SQLite lifecycle ledger",
            "",
        ]

    def _render_srs(self, context: Mapping[str, Any]) -> ArtifactDraft:
        lines = self._header("Generated SRS View", context)
        lines.extend(["## Canonical Requirements", ""])
        lines.extend(self._requirement_rows(context["requirements"], include_statement=True))
        lines.extend(["", "## Goal Graph", ""])
        lines.extend(self._goal_rows(context["graph"]["nodes"]))
        mappings = self._requirement_mappings(context["requirements"])
        mappings += self._goal_mappings(context["graph"]["nodes"])
        return ArtifactDraft(ArtifactKind.SRS, "\n".join(lines).rstrip() + "\n", tuple(mappings))

    def _render_requirements_catalogue(self, context: Mapping[str, Any]) -> ArtifactDraft:
        lines = self._header("Requirements Catalogue", context)
        lines.extend(self._requirement_rows(context["requirements"], include_statement=True))
        return ArtifactDraft(
            ArtifactKind.REQUIREMENTS_CATALOGUE,
            "\n".join(lines).rstrip() + "\n",
            tuple(self._requirement_mappings(context["requirements"])),
        )

    def _render_use_cases(self, context: Mapping[str, Any]) -> ArtifactDraft:
        nodes = [
            node for node in context["graph"]["nodes"] if node.get("node_type") == "use_case"
        ]
        lines = self._header("Use Case Specification", context)
        lines.extend(self._goal_rows(nodes))
        return ArtifactDraft(
            ArtifactKind.USE_CASE_SPECIFICATION,
            "\n".join(lines).rstrip() + "\n",
            tuple(self._goal_mappings(nodes)),
        )

    def _render_sequences(self, context: Mapping[str, Any]) -> ArtifactDraft:
        nodes = [
            node for node in context["graph"]["nodes"] if node.get("node_type") == "sequence"
        ]
        lines = self._header("Sequence Specification", context)
        lines.extend(self._goal_rows(nodes))
        return ArtifactDraft(
            ArtifactKind.SEQUENCE_SPECIFICATION,
            "\n".join(lines).rstrip() + "\n",
            tuple(self._goal_mappings(nodes)),
        )

    def _render_traceability(self, context: Mapping[str, Any]) -> ArtifactDraft:
        lines = self._header("Traceability Matrix", context)
        lines.extend(
            [
                "| Requirement | Status | Revision | Deterministic | Live | Evidence IDs |",
                "| --- | --- | ---: | --- | --- | --- |",
            ]
        )
        for row in context["requirements"]:
            verification = row.get("verification") or {}
            evidence_ids = ", ".join(str(item["evidence_id"]) for item in row.get("evidence", []))
            lines.append(
                "| {requirement_id} | {lifecycle_status} | {current_revision} | {deterministic} | {live} | {evidence_ids} |".format(
                    requirement_id=self._cell(row["requirement_id"]),
                    lifecycle_status=self._cell(row["lifecycle_status"]),
                    current_revision=self._cell(row["current_revision"]),
                    deterministic=self._cell(verification.get("tested_deterministically") or ""),
                    live=self._cell(verification.get("tested_live") or ""),
                    evidence_ids=self._cell(evidence_ids),
                )
            )
        return ArtifactDraft(
            ArtifactKind.TRACEABILITY_MATRIX,
            "\n".join(lines).rstrip() + "\n",
            tuple(self._requirement_mappings(context["requirements"])),
        )

    def _render_milestones(self, context: Mapping[str, Any]) -> ArtifactDraft:
        lines = self._header("Milestone Audit", context)
        lines.extend(
            [
                "| Milestone | Name | Status | Risk | Requirement Scope | Dependency Closure |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        mappings = []
        for milestone in context["milestones"]:
            lines.append(
                "| {milestone_id} | {name} | {status} | {risk} | {requirements} | {closure} |".format(
                    milestone_id=self._cell(milestone["milestone_id"]),
                    name=self._cell(milestone["name"]),
                    status=self._cell(milestone["status"]),
                    risk=self._cell(milestone["risk_disposition"]),
                    requirements=self._cell(", ".join(milestone["requirement_ids"])),
                    closure=self._cell(", ".join(milestone["dependency_closure_ids"])),
                )
            )
            mappings.append(
                ArtifactMapping("milestone", str(milestone["milestone_id"]))
            )
        return ArtifactDraft(ArtifactKind.MILESTONE_AUDIT, "\n".join(lines).rstrip() + "\n", tuple(mappings))

    def _render_phase_audits(self, context: Mapping[str, Any]) -> ArtifactDraft:
        lines = self._header("Phase Audit", context)
        lines.extend(
            [
                "| Audit | Scope | Previous Audit | Policy | Delta Count |",
                "| ---: | --- | ---: | --- | ---: |",
            ]
        )
        mappings = []
        for audit in context["phase_audits"]:
            lines.append(
                "| {audit_id} | {scope_id} | {previous} | {policy} | {delta_count} |".format(
                    audit_id=self._cell(audit["phase_audit_id"]),
                    scope_id=self._cell(audit["scope_id"]),
                    previous=self._cell(audit["previous_phase_audit_id"] or ""),
                    policy=self._cell(audit["policy_version"]),
                    delta_count=self._cell(len(audit["deltas"])),
                )
            )
            mappings.append(ArtifactMapping("phase_audit", str(audit["phase_audit_id"])))
        return ArtifactDraft(ArtifactKind.PHASE_AUDIT, "\n".join(lines).rstrip() + "\n", tuple(mappings))

    @staticmethod
    def _requirement_rows(
        requirements: list[Mapping[str, Any]], *, include_statement: bool
    ) -> list[str]:
        headers = ["| ID | Title | Category | Status | Revision |"]
        separators = ["| --- | --- | --- | --- | ---: |"]
        if include_statement:
            headers = ["| ID | Title | Category | Status | Revision | Statement |"]
            separators = ["| --- | --- | --- | --- | ---: | --- |"]
        lines = headers + separators
        for requirement in requirements:
            values = [
                ArtifactGenerationService._cell(requirement["requirement_id"]),
                ArtifactGenerationService._cell(requirement["title"]),
                ArtifactGenerationService._cell(requirement["category"]),
                ArtifactGenerationService._cell(requirement["lifecycle_status"]),
                ArtifactGenerationService._cell(requirement["current_revision"]),
            ]
            if include_statement:
                values.append(ArtifactGenerationService._cell(requirement["statement"]))
            lines.append("| " + " | ".join(values) + " |")
        return lines

    @staticmethod
    def _goal_rows(nodes: list[Mapping[str, Any]]) -> list[str]:
        lines = ["| Goal | Type | Title | Payload |", "| --- | --- | --- | --- |"]
        for node in nodes:
            lines.append(
                "| {goal_id} | {node_type} | {title} | {payload} |".format(
                    goal_id=ArtifactGenerationService._cell(node["goal_node_id"]),
                    node_type=ArtifactGenerationService._cell(node["node_type"]),
                    title=ArtifactGenerationService._cell(node["title"]),
                    payload=ArtifactGenerationService._cell(
                        json.dumps(node.get("payload") or {}, sort_keys=True)
                    ),
                )
            )
        return lines

    @staticmethod
    def _requirement_mappings(requirements: list[Mapping[str, Any]]) -> list[ArtifactMapping]:
        return [
            ArtifactMapping(
                "requirement",
                str(requirement["requirement_id"]),
                str(requirement.get("source_anchor") or ""),
            )
            for requirement in requirements
        ]

    @staticmethod
    def _goal_mappings(nodes: list[Mapping[str, Any]]) -> list[ArtifactMapping]:
        mappings = []
        for node in nodes:
            anchor = node.get("source_anchor") or ""
            mappings.append(
                ArtifactMapping(
                    "goal_node",
                    str(node["goal_node_id"]),
                    json.dumps(anchor, sort_keys=True) if isinstance(anchor, Mapping) else str(anchor),
                )
            )
        return mappings

    @staticmethod
    def _cell(value: object) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ").strip()
